"""Mako script for generating migration files"""

# revision identifiers, used by Alembic.
revision = 'a8dcbc00d364'
down_revision = '75341357c14a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_verified'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_provider_user_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_oauth_provider_user_id'), 'users', ['oauth_provider', 'oauth_user_id'], unique=False)
    op.create_index(op.f('ix_users_email_verified'), 'users', ['email_verified'], unique=False)
    # ### end Alembic commands ###
